[env]
TERM = "xterm-256color"

[window]
decorations = "full"
startup_mode = "Maximized"
padding = { x = 1, y = 1 }
dynamic_padding = true
opacity = 1.0

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Bold Italic"

[font.offset]
y = 3 

# Kanagawa Dark (Dragon/Wave)
[colors.primary]
background = "#1f1f28" # Sumi Ink 1
foreground = "#dcd7ba" # Fuji White

[colors.cursor]
text   = "#1f1f28"
cursor = "#dcd7ba"

[colors.normal]
black   = "#090618" # Sumi Ink 0
red     = "#c34043" # Autumn Red
green   = "#76946a" # Boatmen Green
yellow  = "#c0a36e" # Carp Yellow
blue    = "#7e9cd8" # Crystal Blue
magenta = "#957fb8" # Oni Violet
cyan    = "#6a9589" # Wave Aqua
white   = "#c8c093" # Old White

[colors.bright]
black   = "#727169" # Village Gray
red     = "#e82424" # Samurai Red
green   = "#98bb6c" # Autumn Green
yellow  = "#e6c384" # Ronin Yellow
blue    = "#7fb4ca" # Sky Blue
magenta = "#938aa9" # Spring Violet
cyan    = "#7aa89f" # Wave Blue
white   = "#dcd7ba" # Fuji White
