# ******************** terminal settings *******************
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set-option -g focus-events on
set-option -sg escape-time 300
set -g mouse on

# ******************** plugins *******************
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'off'
set -g @resurrect-capture-pane-contents 'off'
set -g @resurrect-strategy-nvim 'session'

# ******************** status bar (Kanagawa Lotus) *******************
set -g status on
set -g status-position bottom
set -g status-justify right 
# Status Background updated to #d5cea3
set -g status-style bg=#d5cea3,fg=#545464

set -g status-left-length 50
set -g status-right-length 10

# Session: Midnight Navy #171F40
set -g status-left "#[fg=#171F40] session: #S "

# Window list format: Inactive windows #171F40
set -g window-status-separator "  " 
set -g window-status-format "#[fg=#43436c]#I:#W"

# Current window: Lotus Red highlight
set -g window-status-current-format "#[fg=#c34043]*#I:#W"

set -g status-right " "

# Pane borders: Active border updated to match #171F40
set -g pane-border-style fg=#dcd7ba
set -g pane-active-border-style fg=#171F40

# ******************** remapping ********************
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

unbind %
unbind '"'

bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Resizing
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

# Copy Mode (VI)
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind P paste-buffer
unbind -T copy-mode-vi MouseDragEnd1Pane

set -g base-index 1
setw -g pane-base-index 1

unbind r
bind r source-file ~/.config/tmux/tmux.conf

# ******************** initialize TPM ********************
run '~/.tmux/plugins/tpm/tpm'
